### ISSUE TITLE
Questions about server

### ISSUE THREAD

**Issue by stevenzhang9577** [mc2-project/federated-xgboost#21]
Hi,

I'm following xgboost on federated learning, and when I was trying to run this model, there's something wrong.

When I run 
``python3 serve.py

The error report shows below:

`Starting RPC server on port  50051

Traceback (most recent call last):
  File "serve.py", line 3, in <module>
    fxgb.listen(50051)
  File "/usr/local/lib/python3.7/dist-packages/federatedxgboost-0.90-py3.7.egg/federatedxgboost/remote_server.py", line 126, in listen
    server.wait_for_termination()
  File "/usr/local/lib/python3.7/dist-packages/grpc/_server.py", line 988, in wait_for_termination
    timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/grpc/_common.py", line 141, in wait
    _wait_once(wait_fn, MAXIMUM_WAIT_TIMEOUT, spin_cb)
  File "/usr/local/lib/python3.7/dist-packages/grpc/_common.py", line 106, in _wait_once
    wait_fn(timeout=timeout)
  File "/usr/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)`

Can you help me to check what's happen or which version of grpc you used in this model?

**Comment by chester-leung** [comment]
Hi @stevenzhang9577, can you please paste the exception you're getting? I see the traceback but no explicit exception.
